export const GET_MOVIES_LIST_REQUEST = "GET_MOVIES_LIST_REQUEST";
export const GET_MOVIES_LIST_SUCCESS = "GET_MOVIES_LIST_SUCCESS";

export const ADD_MOVIES_NAME_SUCCESS = "ADD_MOVIES_NAME_SUCCESS";
export const ADD_MOVIES_NAME_REQUEST = "ADD_MOVIES_NAME_REQUEST";

export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";

export const UPDATE_MOVIE_SEAT_SUCCESS = "UPDATE_MOVIE_SEAT_SUCCESS";
export const UPDATE_MOVIE_SEAT_REQUEST = "UPDATE_MOVIE_SEAT_REQUEST";

export const MOVIE_STORE_DATA = "MOVIE_STORE_DATA";